replicaCount: 1
image:
  repository: kvasianovych/kbot
  pullPolicy: IfNotPresent
  tag: "1.0.3-c86bc02"
  arch: "amd64"
service:
  # type: ClusterIP
  type: LoadBalancer
  port: 80
secrets:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
