replicaCount: 1

image:
  repository: kvasianovych/kbot
  pullPolicy: IfNotPresent
  tag: "v1.0.2-c842ffb"
  arch: "amd64"

service:
  type: ClusterIP
  port: 80

secrets:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
